name: tubearchivist
services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist:v0.4.7
    ports:
      - target: 8000
        published: "18000"
        protocol: tcp
    volumes:
      - /opt/media/youtube:/youtube
      - /opt/appdata/$AppID/cache:/cache
    env_file:
      - /opt/appdata/config/tubearchivist.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server:7.2.0-v10
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /opt/appdata/$AppID/redis/data:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es:8.13.2
    container_name: archivist-es
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
      - /opt/appdata/config/tubearchivist-es.env
    volumes:
      - /opt/appdata/$AppID/es/data:/usr/share/elasticsearch/data
    expose:
      - "9200"
x-casaos:
  architectures:
    - amd64
  main: tubearchivist
  category: Media
  description:
    en_us: Your self hosted YouTube media server
  tagline:
    en_us: Your self hosted YouTube media server
  tips: {}
  index: /
  port_map: "8989"
  developer: Tubearchivist
  author: Megavolt Labs
  icon: ''
  thumbnail: ''
  title:
    en_us: Tubearchivist
  project_url: https://tubearchivist.com