name: plex
services:
  plex:
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    environment:
      PGID: $PGID
      PUID: $PUID
      VERSION: docker
    image: linuxserver/plex:1.40.2
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/config
        target: /config
      - type: bind
        source: /opt/media
        target: /media
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: Run Plex as specified uid.
        - container: PGID
          description:
            en_us: Run Plex as specified gid.
        - container: VERSION
          description:
            en_us: Let Docker handle the Plex Version

      volumes:
        - container: /config
          description:
            en_us: Plex config directory.
        - container: /media
          description:
            en_us: Plex Media directory.
    container_name: plex
x-casaos:
  architectures:
    - amd64
    - arm64
  main: plex
  author: Megavolt Labs
  category: Media
  description:
    en_us: Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices. This container is packaged as a standalone Plex Media Server. has always been a top priority. Straightforward design and bulk actions mean getting things done faster.
  developer: Plex
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Plex/icon.png
  screenshot_link: []
  tagline:
    en_us: The home for all your entertainment.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Plex/thumbnail.png
  tips: {}
  title:
    en_us: Plex
  index: /web/index.html
  port_map: "32400"
