name: nginxproxymanager
services:
  nginxproxymanager:
    image: docker.io/jc21/nginx-proxy-manager:latest
    deploy:
      resources:
        reservations:
          memory: "128M"
    network_mode: bridge
    ports:
      - target: 80
        published: "80"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
      - target: 81
        published: "81"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/data
        target: /data
      - type: bind
        source: /opt/appdata/$AppID/etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /opt/appdata/$AppID/cont-init.d/99-themepark
        target: /etc/cont-init.d/99-themepark
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: Nginx HTTP Port

        - container: "443"
          description:
            en_us: Nginx HTTPS Port

        - container: "81"
          description:
            en_us: WebUI Port

      volumes:
        - container: /data
          description:
            en_us: Nginx Proxy Manager data directory.
        - container: /etc/letsencrypt
          description:
            en_us: Nginx Proxy Manager letsencrypt directory.
    container_name: nginxproxymanager
  theme-park:
    # download this: 
    image: ghcr.io/themepark-dev/theme.park
    container_name: theme-park
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - TP_URLBASE=themes
    volumes:
      - /opt/appdata/$AppID/theme-park:/config #optional
    ports:
      - 8080:80
      - 4443:443
    restart: unless-stopped
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: nginxproxymanager
  author: Megavolt Labs
  category: Network
  description:
    en_us: Nginx Proxy Manager is a simple, powerful tool to help you host multiple websites on a single server.
  developer: Nginx Proxy Manager
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/screenshot-3.jpg
  tagline:
    en_us: Managing Nginx proxy hosts with a simple, powerful interface.
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/thumbnail.png
  tips:
    before_install:
      en_us: |
        ⚠️ Warning!
        This is a technical app, please make sure you know what you are doing.
        Nginx Proxy Manager occupies ports 80 and 443 by default for built-in Nginx use. It occupies port 81 for the admin page.
        Please change the CasaOS WebUI port to a port other than 80/81/443. And pay attention to whether the ports conflict with other apps. Otherwise, it may cause your CasaOS to run abnormally.

        Default Administrator User

        | Username | Password |
        | -------- | -------- |
        | `admin@example.com` | `changeme` |
  title:
    en_us: Nginx Proxy Manager
  index: /
  port_map: "81"
