name: radarr
services:
  radarr:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/radarr:5.4.6
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - target: 7878
        published: "7878"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/config
        target: /config
      - type: bind
        source: /opt/media/movies
        target: /movies
      - type: bind
        source: /opt/downloads
        target: /downloads
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: Specify a Timezone to use.
        - container: PUID
          description:
            en_us: Run Radarr as specified uid.
        - container: PGID
          description:
            en_us: Run Radarr as specified gid.
      ports:
        - container: "7878"
          description:
            en_us: WebUI HTTP Port

      volumes:
        - container: /config
          description:
            en_us: Radarr config directory.
        - container: /movies
          description:
            en_us: Radarr movies directory.
        - container: /downloads
          description:
            en_us: Radarr downloads directory.
    container_name: radarr
x-casaos:
  architectures:
    - amd64
    - arm64
  main: radarr
  author: Megavolt Labs
  category: Media
  description:
    en_us: Radarr is a movie collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new movies and will interface with clients and indexers to grab, sort, and rename them. It can also be configured to automatically upgrade the quality of existing files in the library when a better quality format becomes available. Note that only one type of a given movie is supported. If you want both an 4k version and 1080p version of a given movie you will need multiple instances.
  developer: Radarr
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Radarr/icon.png
  screenshot_link: []
  tagline:
    en_us: The movie collection manager for Usenet and BitTorrent users
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Radarr/thumbnail.jpg
  tips: {}
  title:
    en_us: Radarr
  index: /
  port_map: "7878"
