name: lidarr
services:
  lidarr:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Denver
    image: linuxserver/lidarr:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8686
        published: "8686"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/appdata/lidarr/config
        target: /config
      - type: bind
        source: /opt/media/music
        target: /music
      - type: bind
        source: /opt/downloads
        target: /downloads
      - type: bind
        source: /opt/userfiles/jdownloader
        target: /jdownloader
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8686"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /music
          description:
            en_us: ""
        - container: /downloads
          description:
            en_us: ""
    container_name: lidarr
x-casaos:
  architectures:
    - amd64
    - arm64
  main: lidarr
  author: Megavolt Labs
  category: Downloader
  description:
    en_us: Lidarr is a music collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new albums from your favorite artists and will interface with clients and indexers to grab, sort, and rename them. It can also be configured to automatically upgrade the quality of existing files in the library when a better quality format becomes available.
  developer: lidarr Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/screenshot-3.png
  tagline:
    en_us: Music collection manager for Usenet and BitTorrent users
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Lidarr/thumbnail.png
  tips: {}
  title:
    en_us: Lidarr
  port_map: "8686"
