name: draw-io
services:
  app:
    image: jgraph/drawio:24.3.1
    restart: unless-stopped
    environment:
      LETS_ENCRYPT_ENABLED: false
      PUBLIC_DNS: 'draw.squishy.io'
    x-casaos:
      envs: []
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/log/letsencrypt
        target: /var/log/letsencrypt
      - type: bind
        source: /opt/appdata/$AppID/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /opt/appdata/$AppID/lib/letsencrypt
        target: /var/lib/letsencrypt
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: draw-io is free online diagram software. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw-io can import .vsdx, Gliffy™ and Lucidchart™ files.
  tagline:
    en_us: draw-io Is Free Online Diagram Software.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/images/logo.png
  thumbnail: https://raw.githubusercontent.com/jgraph/drawio/dev/src/main/webapp/images/logo.png
  title:
    en_us: Draw.io
  category: Productivity
  port_map: '8090'
