name: readarr
services:
  readarr:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: linuxserver/readarr:0.3.10-develop
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8787
        published: "8787"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/config
        target: /config
        
      - type: bind
        source: /opt/media/books
        target: /books
      - type: bind
        source: /opt/downloads
        target: /downloads
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: "Run Readarr as specified UID"
        - container: PGID
          description:
            en_us: "Run Readarr as specified GID"
        - container: TZ
          description:
            en_us: Specify a Timezone to use.
      ports:
        - container: "8787"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: "Readarr config directory"
        - container: /books
          description:
            en_us: "Readarr books directory"
        - container: /downloads
          description:
            en_us: "Readarr downloads directory"
    container_name: readarr
x-casaos:
  architectures:
    - amd64
    - arm64
  main: readarr
  author: Megavolt Labs
  category: Media
  description:
    en_us: Readarr is a ebook collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new books from your favorite authors and will interface with clients and indexers to grab, sort, and rename them.
  developer: Readarr Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Readarr/icon.png
  screenshot_link: []
  tagline:
    en_us: Ebook and audiobook collection manager for Usenet and BitTorrent users.
  thumbnail: ""
  tips: {}
  title:
    en_us: Readarr
  port_map: "8787"
