name: prowlarr
services:
  prowlarr:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Denver
    image: linuxserver/prowlarr:1.9.4
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 9696
        published: "9696"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "9696"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: ""
    container_name: prowlarr
x-casaos:
  architectures:
    - amd64
    - arm64
  main: prowlarr
  author: CasaOS Team
  category: Downloader
  description:
    en_us: Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports management of both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr offering complete management of your indexers with no per app Indexer setup required (we do it all).
  developer: Prowlarr Team
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Prowlarr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Prowlarr/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Prowlarr/screenshot-2.png
  tagline:
    en_us: Integration of various PVR applications
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Prowlarr/thumbnail.png
  tips: {}
  title:
    en_us: Prowlarr
  port_map: "9696"
