name: traefik
services:
  app:
    image: traefik:v3.0.0
    restart: unless-stopped
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Denver
      TRAEFIK_API: false
      TRAEFIK_API_DASHBOARD: true
      TRAEFIK_API_INSECURE: false
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /opt/appdata/$AppID/config/
        target: /etc/traefik/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Cloud-Native Networking Stack That Just Works.
  tagline:
    en_us: Cloud-native Networking Stack That Just Works.
  developer: ''
  author: Megavolt Labs
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/traefik.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/traefik.png
  title:
    en_us: Traefik
  category: System
  port_map: '8080'
